[package]
name = "mcli"
version = "0.1.0"
authors = ["T. Quigley Malcolm <tqmalcolm@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
